# Generated by Selenium IDE
import pytest
from model.group import Group
from fixture.application import Application


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_testaddgroup(app):
    app.session.login(username="admin", password="secret")
    app.group.create_group(Group(name="fdsfsa", header="fdsfas", footer="fasfs"))
    app.group.return_to_groups_page()
    app.session.logout()


def test_testaddEmptygroup(app):
    app.session.login(username="admin", password="secret")
    app.group.create_group(Group(name="", header="", footer=""))
    app.group.return_to_groups_page()
    app.session.logout()
