# Generated by Selenium IDE
from model.group import Group



def test_testaddgroup(app):
    app.session.login(username="admin", password="secret")
    app.group.create(Group(name="fdsfsa", header="fdsfas", footer="fasfs"))
    app.group.return_to_groups_page()
    app.session.logout()


def test_testaddEmptygroup(app):
    app.session.login(username="admin", password="secret")
    app.group.create(Group(name="", header="", footer=""))
    app.group.return_to_groups_page()
    app.session.logout()
