# Generated by Selenium IDE
import pytest
from group import Group
from application import Application


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_testaddgroup(app):
    app.login(username="admin", password="secret")
    app.create_group(Group(name="fdsfsa", header="fdsfas", footer="fasfs"))
    app.return_to_groups_page()
    app.logout()


def test_testaddEmptygroup(app):
    app.login(username="admin", password="secret")
    app.create_group(Group(name="", header="", footer=""))
    app.return_to_groups_page()
    app.logout()
